### ISSUE TITLE
Merge with Anachron/i3blocks?

### ISSUE THREAD

**Issue by Anachron** [vivien/i3blocks-contrib#169]
Since I am not using i3 anymore we could probably merge https://github.com/Anachron/i3blocks into this repo? What do you think?

**Comment by kb100** [comment]
There are a bunch off scripts in there. Potentially some of them meet the repo requirements, but we won't be merging a whole repo at once. Fork this repo and make pull requests (against the next branch) for the ones you think would be most useful, one PR per block please.

**Comment by Anachron** [comment]
Yeah I don't get your reasoning. I've told you that I am not maintaining my i3blocks collection anymore and you tell me I should add PRs for every block that I think is useful in this repo...

**Comment by vivien** [comment]
Hi @Anachron,

Thanks for your interest in the community. Please note that @kb100 isn’t
simply archiving people’s scripts, he’s actually maintaining them, which
requires a lot a work. Especially since this repo is becoming the place to
store official scripts soon shipped with most distros package of i3blocks.
That’s why this repo has requirements. If you do wish to see some
particular scripts of yours merged there, please send a pull request, one
at a time so discussion can be more efficient. If you do not want to bother
yourself with this process, that is fine too, someone else might be
interested in doing it some day. Thank you!
