### ISSUE TITLE
time parse_bar error STRFTIME_FORMAT

### ISSUE THREAD

**Issue by JonWoodlief** [vivien/i3blocks-contrib#197]
### Expected behavior
Returns the time

### Actual behavior
ERROR parse_bar:162: malformated line: STRFTIME_FORMAT=%Y-%m-%d %H:%M

### i3blocks config relevant to blocklet(s)

command=/home/jon/.rice/scripts/$BLOCK_NAME
separator_block_width=15
markup=none

[time]
interval=1
#TZ_FILE=~/.tz
STRFTIME_FORMAT=%Y-%m-%d %H:%M
TZONES=$DEFAULT_TZ,Brazil/East,Australia/Brisbane,Asia/Calcutta
TZ_LABELS=,Brazil,AU,Hyderabad

### Output of blocklet(s) when run from command line
ERROR parse_bar:162: malformated line: STRFTIME_FORMAT=%Y-%m-%d %H:%M
ERROR main:70: Try 'i3blocks -h' for more information.

**Comment by kb100** [comment]
The error you posted is usually caused by running an out-of-date version of i3blocks that does not yet support dynamics properties. Please see the note on the README about this.

>i3blocks now supports dynamics properties, and all scripts have been updated to do the same. i3blocks-contrib REQUIRES a version of i3blocks that supports dynamics properties, which is currently only available in the git version since the last release (v1.4) was years ago.

Most likely you are trying to use the git version of i3blocks-contrib, but not the git version of i3blocks.
The git version of i3blocks is incredibly easy to compile to please consider that option.
