### ISSUE TITLE
cpu_usage label error

### ISSUE THREAD

**Issue by POTATOES-BoilEm-MashEm-StickEm-inAStew** [vivien/i3blocks-contrib#206]
Hi there!
There is an error in the README.md at the perl cpu_usage blocket. The **label** property is in upper case which results in i3blocks crashing. Change it to _label_ in lower case. I expect i3blocks is case sensitive? 

The reason is that the fourth line **LABEL=CPU** is incorrect and should be **label=CPU**.

### Expected behavior
i3blocks showing the label CPU with it's cpu usage. I have got the _sysstat_ package installed.

### Actual behavior
ERROR parse_bar:162: malformated line: LABEL=CPU 
ERROR main:70: Try 'i3blocks -h' for more information.

### i3blocks config relevant to blocklet(s)
cpu_usage/README.md

### Output of blocklet(s) when run from command line
ERROR parse_bar:162: malformated line: LABEL=CPU 
ERROR main:70: Try 'i3blocks -h' for more information.

### Output of any relevant other commands that might help diagnostics
none

Please be kind, as I'm a beginning programmer and have never really uploaded an issue :o  
Please tell me what to do if I'm doing anything wrong by reporting it (such as creating a pull request instead of issue).

**Comment by jolange** [comment]
You are probably using an older i3blocks version for that block. In the current development version there is no `label` key anymore. But the new block reads the dynamic property `LABEL` from the environment.

For the next time, please include your i3blocks version ;-)

**Comment by kb100** [comment]
@POTATOES-BoilEm-MashEm-StickEm-inAStew Thanks for your report. I believe that @jolange is correct and that you are likely (quite reasonably) using the version of i3blocks provided by your distribution, which is over a year old at this point since i3blocks has not had a new release in over a year. Hopefully we will release a new version in the near future that packagers can package to stop people getting confused about this, but until then you have a few options:

1. Upgrade to the git version of i3blocks (it is very easy! I promise), which is what this repository keeps in sync with
2. Manually lowercase LABEL yourself. Note that this may work for the cpu_usage block, but all blocklets in this repo have been updated to use injected properties, which are only supported in the git version of i3blocks, so you may find that many blocks in this repo fail for you.
3. Check out an older version of this repo from before the time when injected properties are used (it should be easy to find by looking at the commit. The commit messages say e.g. "cpu_usage: use injected properties" or similar. Note that some bugs have been fixed since then, so you will be using a version with known bugs, thought to my knowledge none of them are dangerous bugs.)

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
Thank you! That clears up a lot. Will update i3blocks.
I was doubting if I should have put my i3blocks version in the issue. Perhaps it would be wise to require i3blocks version in the issue template?

**Comment by kb100** [comment]
Unfortunately, the git version of i3blocks still reports version 1.4 instead of 1.4~git@hash or something like that. I should probably make an issue about this.
