### ISSUE TITLE
xkb-layout blocklet: sometimes doesn't change it's state in spite of user's actions

### ISSUE THREAD

**Issue by Lezh1k** [vivien/i3blocks-contrib#401]
### Expected behavior

I use this line in ~/.config/i3 : 
```
exec_always "setxkbmap -model pc104 -layout us,ru -variant ,, -option grp:alt_shift_toggle"
```
And I use xkb-layout blocklet as indicator.
Any time I push alt+shift the indicator of current layout should change it's state.

### Actual behavior
In random moment (sometimes after 2-3 minutes of work, sometimes day or two) it stops work. So I need to press $mod+Shift+R to restart i3. 

### i3blocks config relevant to blocklet(s)
```
[lang]
command=./xkb_layout/xkb_layout
interval=persist
```

### Output of blocklet(s) when run from command line
Command in CLI continue to produce output. Seems like X server somehow drops event subscription after some time. 
There is the code in xkb-switch:
```
 Bool bret = XkbSelectEventDetails(_display, XkbUseCoreKbd,
      XkbStateNotify, XkbAllStateComponentsMask, XkbGroupStateMask)
```
This select creates subscription. Maybe after some time it doesn't work. Maybe the reason is in i3blocks and how it launches persistent blocklets, I don't know.

### THE MAIN QUESTION

Does anybody face this problem? I see this on my 2 laptops, both of them use Arch linux + i3wm. Configs are similar.
If yes - I will search for any tips in i3blocks code for persistent blocklets. If nobody - I guess this issue somehow related to my environment. Just add comments, please :)

**Comment by skidnik** [comment]
Does it hang up on `xkb-switch -w` or `xkb-switch -p`? If `-w` then the event subscription is to blame, if `-p` then the issue may also be caused by the shell pipe used in the script.

Also, the STDERR of the script should end up in the Xorg.log, anything useful there?

`exec 2>"$HOME/cusom.log"` at the start of the script should give you a separate log. Add `set -x` to see script commands executed inside the log.

It used to work perfectly back when I used the **i3-wm** and the **i3blocks** version hasn't changed since then. **xkb-switch** version did. (This doesn't prove much, I know.)

**Comment by Lezh1k** [comment]
It hangs on xkb-switch -w. 
So yes, my idea is to investigate what's happening with event subscription here. 
There is nothing useful in Xorg.log, but I'll try to tail it when this issue appears.

**Comment by Lezh1k** [comment]
Miracle. Works without any error all this time %) 
I'll close ticket for now.
