### ISSUE TITLE
openvpn state always down

### ISSUE THREAD

**Issue by vivien** [vivien/i3blocks-contrib#5]
I'm transfering @boolean-is-null's issue https://github.com/vivien/i3blocks/issues/132 here since the *openvpn* blocklet has been moved to contrib.

**Comment by Nycroth** [comment]
Not a problem. Hey, @boolean-is-null. I just looked over the OpenVPN blocklet but haven't done so thoroughly yet (hence the lack of Wiki documentation for the blocklet). I plan to do so in the next couple days. The script looks like it checks for a pid file for each OpenVPN connection `/run/openvpn/*.pid`. This is how it checks if you have tunnels or not. Can you double check if these files exist?

**Comment by boolean-is-null** [comment]
Thank you for the feedback and the effort, really appreciated!
I've just checked and the file /run/openvpn/servername.pid exists and the tun0 device is up..

**Comment by boolean-is-null** [comment]
I'm not familiar with perl, nor the used script, but on my system the mentioned scripts (I guess):

    my $openvpn_enabled='/dev/shm/openvpn_i3blocks_enabled';
    my $openvpn_disabled='/dev/shm/openvpn_i3blocks_disabled';

do not really exist. `openvpn_i3blocks_disabled` is empty and `openvpn_i3blocks_enabled` doesn't exist at all.

PID files definitely exist as `/run/openvpn/*.pid`

**Comment by Nycroth** [comment]
Sorry, I've been busy since the start of school.

The OpenVPN script. If it finds the PID file, it opens it and pulls out the PID. Then it checks the command line of the process `/proc/$PID/cmdline` for `/--config\s*(.*\.conf)/` that is, it checks for the config.

From this config it looks for a `dev` declaration and pulls the interface from `/dev\s+(\w+)/`. Next it checks to see if `/sys/class/net/$interface` exists. If so, it will display that your VPN is up. If not, it assumes it is down.

To test, between lines 94 and 95, insert the following:
```perl
# check if interface exist
print "$interface"
unless ($interface eq 'null') {
```

Then run the script. If you see an interface, see if `/sys/class/net/$interface` exists. If not, then this script will never work for you. If interface is null, check your config to ensure you have a line `dev $interface`.

**Comment by boolean-is-null** [comment]
aaah! Thank you very much for this extensive explanation!

It works now, I had the problem that I ran the `openvpn` without `--config`, I just used `openvpn configfile`. During the testing I also used a config file ending in `.ovpn` which I overlooked.

off topic: any clue why the PID files are not deleted for me, when the VPN disconnects?

**Comment by Nycroth** [comment]
Haha, I wish I could help there. You would need to check with OpenVPN about that. The PID file is its responsibility.

**Comment by kb100** [comment]
"It works now" assuming this means the issue has been resolved. Reopen if it is not resolved.
