### ISSUE TITLE
Compiled programs in “contrib”

### ISSUE THREAD

**Issue by Zopieux** [vivien/i3blocks-contrib#6]
Hello fellow contributors,

I see that [repo standards](https://github.com/vivien/i3blocks-contrib/wiki/Repo-Standards) allow for *compiled* programs. I wrote a smallish C script that uses libpulse and listens for changes in pulseaudio sinks so the volume stays up-to-date whenever something changes, even if there is no signal sent to i3blocks (for instance, you cannot send a signal when changing volume in `pavucontrol`). That would work fine with `interval=persist` blocks and is near to impossible to do using shell scripts. Would you be interested in that kind of “blocklets“?

Please note that in this particular example, it would compete with the built-in `volume` script, but I guess I could just name it `pulse-volume`.

**Comment by kb100** [comment]
I personally have nothing against multiple scripts attempting to accomplish the same things. In fact, I think it's a great idea. Some people just have different philosophies about how the same thing should work. There is no reason to require a monopoly. That said, I don't know how we should handle naming to avoid conflict.

As for the compiled part, the main thing we care about is code readability. If we can understand and review your code then using a compiled language in a situation where doing so offers great advantage is fine. The other issue we have is that we want to make it easy on the user, so make sure that you carefully list dependencies, and ideally include a Makefile.

**Comment by Zopieux** [comment]
Of course. Source is already pretty clean, I would just need to adapt the Makefile a bit. I guess I will send a PR soon and we'll see how things go.

---
In this case, there is no real conflict between built-in `volume` and my script. While `volume` uses `amixer` to read the value, my script is pulseaudio specific — although many people use that mixer nowadays.

**Comment by vivien** [comment]
I agree with both of you. I'm totally fine with a `volume` blocklet in contrib, since we don't expect a default `foo` script and `contrib/foo` to be the same. Go with the name of your choice, something like "pulse" or having a "volume {pre,suf}fix, that's really up to you.

If there's no dependency, `make foo` may be enough to compile `foo`. If not, please provide a portable Makefile. As @kb100 mentioned, make sure to add concise doc in a README.md file.

Thanks!

**Comment by Zopieux** [comment]
https://github.com/Zopieux/i3blocks-contrib/tree/master/pulse-volume

Not PRing here yet but here is what I got so far. Not sure about the portability of the Makefile but it's dead simple. Thanks for your feedback!

**Comment by vivien** [comment]
Indeed clicks won't affect an already running spawned block. Since i3blocks is basically just a scheduler, user input (timeout, signal or click) should just be used to trigger the block command.

However i3blocks is aware of the pid of the persistent block being clicked, so it is discutable though.

It is a complex question that may introduce non-intuitive behavior for small value, especially since you have several buttons. Here are some options.

 * i3blocks can signal the process with an user-defined signal. This implies one new property per button value (`button1=10`, etc.)
 * i3blocks can execute a different script on click, passing the process ID (e.g. `click=$BLOCK_COMMAND`). This may default to the block command. Not sure it would be very consistent. In which case should/shoudn't we care about the output?

Not sure that any of these options will be simple and intuitive to every users and cover all use cases. I cannot really find a valid use case for persistency + click. Looks like a adjacent "button" would do the job. What are you trying to accomplish by clicking on your persistent block?

**Comment by kb100** [comment]
Might I suggest an alternative to using C for this blocklet? Pulseaudio stores device volumes, configurations, etc. in the user's .config/pulse directory, so one can simply use

    while true; do
        inotifywait /home/$USER/.config/pulse
        # your volume script here
    done

This can either be part of your script (if you do not care about clicks), or you could use 

    while true; do
        inotifywait /home/$USER/.config/pulse
        pkill -RTMIN+1 i3blocks
    done

as a daemon that just signals i3blocks to update the volume block. In this setup clicks will work fine, as the thing that is waiting for pulse updates is not the same thing that is giving output to i3bar.

**Comment by kb100** [comment]
Compiled programs are allowed, so long as the source is readable and compilation & install instructions are clear.
